### ISSUE TITLE
Documentation, please

### ISSUE THREAD

**Issue by eMPee584** [langner/wok_search#1]
Is this an "internal" research project only for your personal use, or does it work in general and could be of use to others? If so, please add some docs, at least a README :+1: thx

**Comment by langner** [comment]
Hi there. Yes and no. I wrote the code for internal use, and it is only one component of a larger production system (research support). However, it has become sufficiently general and abstract that I decided to publish it.

I've added a note to the README and a simple usage example as well. But I am not willing to invest more time in that direction. Please read the code to get an idea of how to use it further. Contributions are welcome.

You might also be interested in some smaller bits of the system I've published in gists:
https://gist.github.com/langner/7820246
https://gist.github.com/langner/9e732e662b81d45af52a
https://gist.github.com/langner/ce600127262b04db82d2
https://gist.github.com/langner/08164c88bb37cb18b6d1
https://gist.github.com/langner/2aabb6e3f7ee3b6d477e
